/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as PacksRouteImport } from './routes/packs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ServersIndexRouteImport } from './routes/servers/index'
import { Route as PacksIndexRouteImport } from './routes/packs/index'
import { Route as SettingsSshKeysRouteImport } from './routes/settings/ssh-keys'
import { Route as SettingsServerRouteImport } from './routes/settings/server'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as ServersNewRouteImport } from './routes/servers/new'
import { Route as ServersServerIdRouteImport } from './routes/servers/$serverId'
import { Route as PacksNewRouteImport } from './routes/packs/new'
import { Route as PacksPackIdEditRouteImport } from './routes/packs/$packId.edit'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksRoute = PacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ServersIndexRoute = ServersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServersRoute,
} as any)
const PacksIndexRoute = PacksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PacksRoute,
} as any)
const SettingsSshKeysRoute = SettingsSshKeysRouteImport.update({
  id: '/ssh-keys',
  path: '/ssh-keys',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsServerRoute = SettingsServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)
const ServersNewRoute = ServersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ServersRoute,
} as any)
const ServersServerIdRoute = ServersServerIdRouteImport.update({
  id: '/$serverId',
  path: '/$serverId',
  getParentRoute: () => ServersRoute,
} as any)
const PacksNewRoute = PacksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PacksRoute,
} as any)
const PacksPackIdEditRoute = PacksPackIdEditRouteImport.update({
  id: '/$packId/edit',
  path: '/$packId/edit',
  getParentRoute: () => PacksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/packs': typeof PacksRouteWithChildren
  '/servers': typeof ServersRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/packs/new': typeof PacksNewRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/servers/new': typeof ServersNewRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/server': typeof SettingsServerRoute
  '/settings/ssh-keys': typeof SettingsSshKeysRoute
  '/packs/': typeof PacksIndexRoute
  '/servers/': typeof ServersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/packs/$packId/edit': typeof PacksPackIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/packs/new': typeof PacksNewRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/servers/new': typeof ServersNewRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/server': typeof SettingsServerRoute
  '/settings/ssh-keys': typeof SettingsSshKeysRoute
  '/packs': typeof PacksIndexRoute
  '/servers': typeof ServersIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/packs/$packId/edit': typeof PacksPackIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/packs': typeof PacksRouteWithChildren
  '/servers': typeof ServersRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/packs/new': typeof PacksNewRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/servers/new': typeof ServersNewRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/server': typeof SettingsServerRoute
  '/settings/ssh-keys': typeof SettingsSshKeysRoute
  '/packs/': typeof PacksIndexRoute
  '/servers/': typeof ServersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/packs/$packId/edit': typeof PacksPackIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/packs'
    | '/servers'
    | '/settings'
    | '/setup'
    | '/packs/new'
    | '/servers/$serverId'
    | '/servers/new'
    | '/settings/account'
    | '/settings/server'
    | '/settings/ssh-keys'
    | '/packs/'
    | '/servers/'
    | '/settings/'
    | '/packs/$packId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/packs/new'
    | '/servers/$serverId'
    | '/servers/new'
    | '/settings/account'
    | '/settings/server'
    | '/settings/ssh-keys'
    | '/packs'
    | '/servers'
    | '/settings'
    | '/packs/$packId/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/packs'
    | '/servers'
    | '/settings'
    | '/setup'
    | '/packs/new'
    | '/servers/$serverId'
    | '/servers/new'
    | '/settings/account'
    | '/settings/server'
    | '/settings/ssh-keys'
    | '/packs/'
    | '/servers/'
    | '/settings/'
    | '/packs/$packId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PacksRoute: typeof PacksRouteWithChildren
  ServersRoute: typeof ServersRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs': {
      id: '/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/servers/': {
      id: '/servers/'
      path: '/'
      fullPath: '/servers/'
      preLoaderRoute: typeof ServersIndexRouteImport
      parentRoute: typeof ServersRoute
    }
    '/packs/': {
      id: '/packs/'
      path: '/'
      fullPath: '/packs/'
      preLoaderRoute: typeof PacksIndexRouteImport
      parentRoute: typeof PacksRoute
    }
    '/settings/ssh-keys': {
      id: '/settings/ssh-keys'
      path: '/ssh-keys'
      fullPath: '/settings/ssh-keys'
      preLoaderRoute: typeof SettingsSshKeysRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/server': {
      id: '/settings/server'
      path: '/server'
      fullPath: '/settings/server'
      preLoaderRoute: typeof SettingsServerRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/servers/new': {
      id: '/servers/new'
      path: '/new'
      fullPath: '/servers/new'
      preLoaderRoute: typeof ServersNewRouteImport
      parentRoute: typeof ServersRoute
    }
    '/servers/$serverId': {
      id: '/servers/$serverId'
      path: '/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof ServersServerIdRouteImport
      parentRoute: typeof ServersRoute
    }
    '/packs/new': {
      id: '/packs/new'
      path: '/new'
      fullPath: '/packs/new'
      preLoaderRoute: typeof PacksNewRouteImport
      parentRoute: typeof PacksRoute
    }
    '/packs/$packId/edit': {
      id: '/packs/$packId/edit'
      path: '/$packId/edit'
      fullPath: '/packs/$packId/edit'
      preLoaderRoute: typeof PacksPackIdEditRouteImport
      parentRoute: typeof PacksRoute
    }
  }
}

interface PacksRouteChildren {
  PacksNewRoute: typeof PacksNewRoute
  PacksIndexRoute: typeof PacksIndexRoute
  PacksPackIdEditRoute: typeof PacksPackIdEditRoute
}

const PacksRouteChildren: PacksRouteChildren = {
  PacksNewRoute: PacksNewRoute,
  PacksIndexRoute: PacksIndexRoute,
  PacksPackIdEditRoute: PacksPackIdEditRoute,
}

const PacksRouteWithChildren = PacksRoute._addFileChildren(PacksRouteChildren)

interface ServersRouteChildren {
  ServersServerIdRoute: typeof ServersServerIdRoute
  ServersNewRoute: typeof ServersNewRoute
  ServersIndexRoute: typeof ServersIndexRoute
}

const ServersRouteChildren: ServersRouteChildren = {
  ServersServerIdRoute: ServersServerIdRoute,
  ServersNewRoute: ServersNewRoute,
  ServersIndexRoute: ServersIndexRoute,
}

const ServersRouteWithChildren =
  ServersRoute._addFileChildren(ServersRouteChildren)

interface SettingsRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsServerRoute: typeof SettingsServerRoute
  SettingsSshKeysRoute: typeof SettingsSshKeysRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsServerRoute: SettingsServerRoute,
  SettingsSshKeysRoute: SettingsSshKeysRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PacksRoute: PacksRouteWithChildren,
  ServersRoute: ServersRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
