/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PacksRouteImport } from './routes/packs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServersNewRouteImport } from './routes/servers/new'
import { Route as ServersServerIdRouteImport } from './routes/servers/$serverId'

const PacksRoute = PacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersNewRoute = ServersNewRouteImport.update({
  id: '/servers/new',
  path: '/servers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersServerIdRoute = ServersServerIdRouteImport.update({
  id: '/servers/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/packs': typeof PacksRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/servers/new': typeof ServersNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/packs': typeof PacksRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/servers/new': typeof ServersNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/packs': typeof PacksRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/servers/new': typeof ServersNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/packs' | '/servers/$serverId' | '/servers/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/packs' | '/servers/$serverId' | '/servers/new'
  id: '__root__' | '/' | '/packs' | '/servers/$serverId' | '/servers/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PacksRoute: typeof PacksRoute
  ServersServerIdRoute: typeof ServersServerIdRoute
  ServersNewRoute: typeof ServersNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/packs': {
      id: '/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/new': {
      id: '/servers/new'
      path: '/servers/new'
      fullPath: '/servers/new'
      preLoaderRoute: typeof ServersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/$serverId': {
      id: '/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof ServersServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PacksRoute: PacksRoute,
  ServersServerIdRoute: ServersServerIdRoute,
  ServersNewRoute: ServersNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
